# Generated by Django 2.2.6 on 2019-10-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProgramando', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_vivienda',
            new_name='tipoVivienda',
        ),
    ]
