# Generated by Django 2.2.6 on 2019-10-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProgramando', '0002_auto_20191014_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipoCurso',
            field=models.CharField(default='python', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='python', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProgramando.Curso'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProgramando.Usuario'),
        ),
    ]
