# Generated by Django 2.2.6 on 2019-11-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProgramando', '0004_auto_20191115_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursosPrograman2'),
        ),
    ]
