# Generated by Django 2.2.6 on 2019-11-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProgramando', '0006_auto_20191115_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursosPrograman2', verbose_name='imagen'),
        ),
    ]
